### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by afonsopacifer** [afonsopacifer/new-game#1]
## Tasks
- [x] Refactor All old features/tasks
- [x] Change all for slush-tangerine
- [x] Transform the boilerplate in a slush generator
- [ ] Add travis config file
- [ ] Update jade for pug
- [ ] Update all deprecated dependencies
- [ ] Pug Lint
- [ ] CSS Lint
- [ ] Update Documents (**All** gulp tasks)
- [x] Update folders structure
- [ ] Offline First
- [ ] Single Page Application?
- [ ] Style Guide for Design - [mdcss](https://github.com/jonathantneal/mdcss)
- [ ] Style Guide for Code
- [ ] Performance tests
- [ ] Add babelJS config (babelrc?)
- [ ] Add visual regression tests with BackstopJS
